# Generated by Django 6.0.6 on 2026-09-25 15:27

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant_app', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                'verbose_name': 'Wissensabschnitt',
                'verbose_name_plural': 'Wissensabschnitte',
                'ordering': ['source', 'position'],
                'indexes': [pgvector.django.indexes.HnswIndex(fields=['embedding'], name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
