"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

load_dotenv()


def env_bool(name, default="False"):
    """Read a boolean from the environment ('True'/'1'/'yes' are truthy)."""
    value = os.getenv(name, default).strip().lower()
    return value in ("true", "1", "yes", "on")


def env_list(name, default=""):
    """Read a comma separated list from the environment."""
    return [item.strip()
            for item in os.getenv(name, default).split(",")
            if item.strip()]


def env_probability(name, default):
    """Read a number greater than 0 and at most 1 from the environment."""
    raw = os.getenv(name, default)
    try:
        value = float(raw)
    except ValueError:
        raise ValueError(f"{name} must be a number, got {raw!r}.") from None
    if not 0 < value <= 1:
        raise ValueError(
            f"{name} must be greater than 0 and at most 1, got {raw!r}."
        )
    return value


SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set in the environment variables.")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True so the local development setup keeps working unchanged.
DEBUG = env_bool("DEBUG", "True")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'corsheaders',
    'rest_framework',
    'auth_app',
    'rest_framework.authtoken',
    'offers_app',
    'orders_app',
    'reviews_app',
    'base_app',
    'contact_app',
    'assistant_app',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5500,http://127.0.0.1:5500",
)

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# PostgreSQL is required: the portfolio assistant stores its vectors with
# pgvector, which SQLite does not have. Locally it runs in Docker.

if not os.getenv("DB_NAME"):
    raise ValueError(
        "DB_NAME is not set in the environment variables. Copy .env.example "
        "to .env and start the database with: docker compose up -d"
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

_PASSWORD_VALIDATION = 'django.contrib.auth.password_validation'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': f'{_PASSWORD_VALIDATION}.UserAttributeSimilarityValidator'},
    {'NAME': f'{_PASSWORD_VALIDATION}.MinimumLengthValidator'},
    {'NAME': f'{_PASSWORD_VALIDATION}.CommonPasswordValidator'},
    {'NAME': f'{_PASSWORD_VALIDATION}.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# When the app is served from a subpath (e.g. /coderr), set FORCE_SCRIPT_NAME
# to that prefix. Django then prefixes the relative STATIC_URL and MEDIA_URL
# below automatically, and reverse() generates correct URLs.
FORCE_SCRIPT_NAME = os.getenv("FORCE_SCRIPT_NAME") or None

# Keep STATIC_URL and MEDIA_URL relative (no leading slash) so that
# FORCE_SCRIPT_NAME is applied to them.
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_RATES': {
        'contact': '5/hour',
        'assistant': '20/hour',
        'assistant_global': '200/day',
    },
}


# Cache
# The database cache is shared across all Gunicorn workers, so the
# throttling above counts correctly no matter which worker answers.
# Create the table once with: manage.py createcachetable

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    }
}


# Email
# Without EMAIL_HOST_USER the console backend is used, so local
# development prints mails to the terminal instead of sending them.

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", "True")
EMAIL_TIMEOUT = 15

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
CONTACT_RECIPIENT = os.getenv("CONTACT_RECIPIENT", "")

if not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Portfolio assistant
# Off by default, so a server without the embedding service answers 503
# instead of failing on every request.

ASSISTANT_ENABLED = env_bool("ASSISTANT_ENABLED")

# Sections below this cosine similarity count as off topic. Measured with
# evaluate_retrieval: the weakest question on topic scored 0.774.
ASSISTANT_MIN_SIMILARITY = env_probability("ASSISTANT_MIN_SIMILARITY", "0.76")

# Language model that writes the answers. The profile picks model and
# thinking, see assistant_app/llm_client.py; evaluate_answers compares them.
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
ASSISTANT_LLM_PROFILE = os.getenv(
    "ASSISTANT_LLM_PROFILE", "haiku-5-5-thinking"
)


# Embedding service
# Runs as its own process next to Django, see embedding_service/README.md.

EMBEDDING_SERVICE_URL = os.getenv(
    "EMBEDDING_SERVICE_URL", "http://127.0.0.1:8002"
)


# Laya input filter
# Runs as its own process next to Django, see laya_service/README.md.
# A question is rejected when its jailbreak score reaches the threshold.
# 0.8 was measured with evaluate_guard: no genuine question reached it.
# A threshold above 1 would let every attack through, so env_probability
# stops the startup instead.

LAYA_SERVICE_URL = os.getenv("LAYA_SERVICE_URL", "http://127.0.0.1:8001")
LAYA_THRESHOLD = env_probability("LAYA_THRESHOLD", "0.8")


SPECTACULAR_SETTINGS = {
    'TITLE': 'Coderr API',
    'DESCRIPTION': 'Backend API for the Coderr freelancer platform.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


AUTH_USER_MODEL = "auth_app.User"


MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Security settings for production
# Only applied when DEBUG is off, so local development is unaffected.
# Nginx terminates TLS and forwards X-Forwarded-Proto, therefore Django needs
# to be told that the original request was HTTPS.

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'
    # HSTS is cached by browsers, so it stays off until HTTPS is verified.
    # Enable it afterwards by setting HSTS_SECONDS=31536000 in the .env file.
    SECURE_HSTS_SECONDS = int(os.getenv("HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("HSTS_INCLUDE_SUBDOMAINS")


# Logging
# Everything goes to stdout/stderr so that it ends up in the systemd journal
# and can be read with: journalctl -u gunicorn -f

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
