# Generated by Django 6.0.6 on 2026-09-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip_address',
        ),
    ]
