server {
    server_name coderr.benjaminblarr.de;

    root /var/www/coderr/frontend;
    index index.html;

    client_max_body_size 10M;

    access_log /var/log/nginx/coderr.access.log;
    error_log  /var/log/nginx/coderr.error.log;

    location /api/ {
        proxy_pass http://unix:/run/gunicorn/coderr.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /admin/ {
        proxy_pass http://unix:/run/gunicorn/coderr.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ {
        alias /var/www/coderr/backend/staticfiles/;
        expires 30d;
        access_log off;
    }

    location /media/ {
        alias /var/www/coderr/backend/media/;
        expires 7d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/coderr.benjaminblarr.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/coderr.benjaminblarr.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = coderr.benjaminblarr.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name coderr.benjaminblarr.de;
    return 404; # managed by Certbot


}